text = input("Type something: ")
print("You type: ", text)
print("Each input is a String and you need casting to use other types: ")
num = int(input("Type a number: "))
print(num)
let = input("Type a letter: ")[0]
print(let)
flo = float(input("Type a decimal: "))
print(flo)
print("Do not forget to specify the casting if you want to read ", end="")
print("a different type from a string.")