print("It is time to show more list methods for python:")
example = [1,2,3,4]
print(f"\n* <list>.append(element): Insert the element in the last position --> example.append(5): {example.append(6)} ")
print(f"\n* <list>.insert(pos, element): Insert the element in the position given --> example.insert(3,4): {example.insert(1,5)}")
print(f"\n* <list>.pop(pos): Delete the value in the position given --> example.pop(3): {example.pop(3)}")
print(f"\n* <list>.remove(element): Delete the first coincidence with the element given --> example.remove(1): {example.remove(1)}")
print(f"\n* <list>.index(element): Return the position of the element (if it exists) --> example.index(5): {example.index(5)}")
print("You can also specify between range to give the index: index(element,begin,end)")
print(f"\n* <list>.count(element): Return the number of the coincidences with the element --> example.count(1): {example.count(1)}")
print(f"\n* <list>.sort(): Organize the list (least to greatest) --> example.sort(): {example.sort()} ")
print("You can reverse the order for sort if you set .sort(reverse = True) or just use <list>.reverse()")
copy = example.copy()
print(f"\n* Example: {example} and Copy: {copy}")
print(f"<list>.copy(): Generates a copy of a list:\nWe have: id(example): {id(example)} and id(copy): {id(copy)}")
print(f"\n* Finally, if you want to clear an array you use <list>.clear() --> Example: {example.clear()}")